### ISSUE TITLE
MKS Drill 1A cannot be loaded, base gets deleted

### ISSUE THREAD

**Issue by HighTechPizza** [judicator/SimpleRepaint#1]
Heyo, i have a bunch of mods in KSP (ckan file attached), working good together. I wanted to improve basebuilding by more color variation.
But withSimple Repaint, when I want to load my save, "MKS Drill 1A cannot be loaded" warning appears and the base gets completely removed if pressing "okay".

No drama, got backup files, but would be nice if i could repaint all kinds of parts

**Comment by judicator** [comment]
Yep, that's notorius "part is not supported by B9PartSwitch" bug. Thanks for your report!
I added three drills from MKS mod to so-called grey list, so they get repainting via stock part variants. Here is how it look in game:
![Drill repainting](https://i.imgur.com/ZFSveJj.png)

Fixed in 0.4.2.
